import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  settlementShares,
  redeemValue,
  quoteLegs,
  turboLeverage,
  strikeForLeverage,
  floorDiscountBps,
  annualisedFundingBps,
  classifyMultiplier,
  adjustStrike,
  formatUsd,
  parseUsd,
  formatLeverage,
  maturityFor,
  tradingDayFor,
  WAD,
} from "../src/math.js";

const here = dirname(fileURLToPath(import.meta.url));

type Fixture =
  | {
      kind: "settlement";
      closeX8: string;
      strikeX8: string;
      floorPerUnit: string;
      turboPerUnit: string;
    }
  | {
      kind: "classification";
      from: string;
      to: string;
      result: string;
      ratioNum: string;
      ratioDen: string;
      adjusted170: string;
    };

const fixtures: Fixture[] = JSON.parse(readFileSync(join(here, "fixtures.json"), "utf8"));

/**
 * The fixture is generated by `contracts/test/Fixtures.t.sol` from the contracts themselves. These
 * assertions are the only thing keeping the SDK's arithmetic from drifting away from the
 * arithmetic that actually pays people.
 */
describe("parity with the contracts", () => {
  const settlements = fixtures.filter((f) => f.kind === "settlement");
  const classifications = fixtures.filter((f) => f.kind === "classification");

  it("has a fixture to check against", () => {
    expect(settlements.length).toBeGreaterThan(0);
    expect(classifications.length).toBeGreaterThan(0);
  });

  it.each(settlements)("settles $closeX8 against strike $strikeX8 exactly as Series.sol does", (f) => {
    const shares = settlementShares(BigInt(f.closeX8), BigInt(f.strikeX8));
    expect(shares.floorPerUnit).toBe(BigInt(f.floorPerUnit));
    expect(shares.turboPerUnit).toBe(BigInt(f.turboPerUnit));
  });

  it.each(classifications)("classifies $to exactly as MultiplierAccountant.sol does", (f) => {
    const c = classifyMultiplier(BigInt(f.from), BigInt(f.to));
    expect(c.kind).toBe(f.result);
    expect(c.ratioNum).toBe(BigInt(f.ratioNum));
    expect(c.ratioDen).toBe(BigInt(f.ratioDen));
    expect(adjustStrike(17000000000n, c)).toBe(BigInt(f.adjusted170));
  });
});

describe("settlement", () => {
  it("always divides the vault into two shares that sum to one", () => {
    for (const close of [1n, 100n, 17000000000n, 99999999999999n]) {
      const s = settlementShares(close, 17000000000n);
      expect(s.floorPerUnit + s.turboPerUnit).toBe(WAD);
    }
  });

  it("gives FLOOR the whole vault below the split point", () => {
    const s = settlementShares(parseUsd("120.00"), parseUsd("170.00"));
    expect(s.floorPerUnit).toBe(WAD);
    expect(s.turboPerUnit).toBe(0n);
  });

  it("gives TURBO the upside above it", () => {
    const s = settlementShares(parseUsd("200.00"), parseUsd("170.00"));
    expect(s.turboPerUnit).toBe(WAD - (parseUsd("170.00") * WAD) / parseUsd("200.00"));
  });

  it("rejects a zero close rather than dividing by it", () => {
    expect(() => settlementShares(0n, parseUsd("170.00"))).toThrow(RangeError);
  });

  it("pays a mixed holding the sum of both claims", () => {
    const s = settlementShares(parseUsd("200.00"), parseUsd("170.00"));
    // 100 FLOOR at 0.85 plus 100 TURBO at 0.15 is the 100 stock they were minted from.
    expect(redeemValue(s, 100n * WAD, 100n * WAD)).toBe(100n * WAD);
  });
});

describe("leverage", () => {
  it("is about 21x for a 170 strike against a 178.50 share", () => {
    expect(formatLeverage(turboLeverage(parseUsd("178.50"), parseUsd("170.00")))).toBe("21.0x");
  });

  it("is undefined rather than infinite at or below the strike", () => {
    expect(turboLeverage(parseUsd("170.00"), parseUsd("170.00"))).toBe(0n);
    expect(turboLeverage(parseUsd("100.00"), parseUsd("170.00"))).toBe(0n);
  });

  it("round-trips through strikeForLeverage", () => {
    const spot = parseUsd("178.50");
    const strike = strikeForLeverage(spot, 20n * WAD);
    // Within a cent of the requested leverage, which is all an 1e8 strike can express.
    expect(formatLeverage(turboLeverage(spot, strike))).toBe("20.0x");
  });

  it("refuses a leverage at or below 1x, which no split point produces", () => {
    expect(() => strikeForLeverage(parseUsd("178.50"), WAD)).toThrow(RangeError);
  });
});

describe("the funding rate", () => {
  it("is FLOOR's discount to its own claim", () => {
    // FLOOR claiming $170 trading at $168.30 is a 1% discount.
    expect(floorDiscountBps(parseUsd("168.30"), parseUsd("170.00"))).toBe(100n);
  });

  it("is zero when FLOOR trades at or above its claim", () => {
    expect(floorDiscountBps(parseUsd("170.00"), parseUsd("170.00"))).toBe(0n);
    expect(floorDiscountBps(parseUsd("171.00"), parseUsd("170.00"))).toBe(0n);
  });

  it("annualises so series of different tenors compare", () => {
    // 1% over 30 days is a bit over 12% a year.
    expect(annualisedFundingBps(100n, 30)).toBe(1216n);
    expect(annualisedFundingBps(100n, 365)).toBe(100n);
  });

  it("does not divide by a zero tenor", () => {
    expect(annualisedFundingBps(100n, 0)).toBe(0n);
  });
});

describe("leg values", () => {
  it("sum to the multiplier-adjusted share price, and never exceed it", () => {
    const multiplier = 1_000_775_159_164_630_595n;
    const price = parseUsd("178.50");
    const whole = (price * multiplier) / WAD;
    const { floorValueX8, turboValueX8 } = quoteLegs(price, parseUsd("170.00"), multiplier);

    // Each leg floors independently, so the pair can land one wei under the whole. The direction
    // is the part that matters: a sum ABOVE the underlying would be value the vault does not hold.
    // `Series.sol` carries the same one-wei tolerance, and `redeem()` pays the final redeemer the
    // vault's whole remaining balance so the dust is never retained.
    expect(floorValueX8 + turboValueX8).toBeLessThanOrEqual(whole);
    expect(whole - (floorValueX8 + turboValueX8)).toBeLessThanOrEqual(1n);
  });

  it("never sums above the underlying at any price", () => {
    const multiplier = 1_000_775_159_164_630_595n;
    for (const p of ["0.01", "1.00", "169.99", "170.00", "170.01", "1000.00", "99999.99"]) {
      const price = parseUsd(p);
      const { floorValueX8, turboValueX8 } = quoteLegs(price, parseUsd("170.00"), multiplier);
      expect(floorValueX8 + turboValueX8).toBeLessThanOrEqual((price * multiplier) / WAD);
    }
  });

  it("hands a distribution to FLOOR and leaves TURBO untouched", () => {
    const strike = parseUsd("170.00");
    const price = parseUsd("178.50");
    const before = quoteLegs(price, strike, WAD);
    const after = quoteLegs(price, strike, 1_010_000_000_000_000_000n);
    expect(after.floorValueX8).toBeGreaterThan(before.floorValueX8);
    // TURBO scales with the multiplier too, but its strike-relative claim is unchanged.
    expect(after.turboValueX8 - before.turboValueX8).toBe(
      ((price - strike) * 10_000_000_000_000_000n) / WAD,
    );
  });
});

describe("corporate actions", () => {
  it("reads the live NVDA accrual as a dividend", () => {
    expect(classifyMultiplier(WAD, 1_000_775_159_164_630_595n).kind).toBe("dividend");
  });

  it("refuses to guess at a dirty ratio", () => {
    expect(classifyMultiplier(WAD, 1_373_000_000_000_000_000n).kind).toBe("unknown");
  });

  it("reports a doubling as 2:1, not 4:2", () => {
    const c = classifyMultiplier(WAD, 2n * WAD);
    expect([c.ratioNum, c.ratioDen]).toEqual([2n, 1n]);
  });

  it("only ever moves a strike on a split", () => {
    for (const to of [WAD, 1_000_775_159_164_630_595n, 1_373_000_000_000_000_000n]) {
      const c = classifyMultiplier(WAD, to);
      expect(adjustStrike(parseUsd("170.00"), c)).toBe(parseUsd("170.00"));
    }
  });
});

describe("formatting", () => {
  it("round-trips USD", () => {
    for (const s of ["178.50", "0.01", "1000.00", "170.00"]) {
      expect(formatUsd(parseUsd(s))).toBe(s);
    }
  });

  it("parses a value with no fractional part", () => {
    expect(parseUsd("170")).toBe(17000000000n);
  });

  it("drops the decimal point entirely at zero places", () => {
    // The payoff chart's split-point label asks for whole dollars, and a bare trailing dot in
    // "split 170." reads as a truncation bug to anyone looking at it.
    expect(formatUsd(parseUsd("170.00"), 0)).toBe("170");
    expect(formatUsd(parseUsd("178.50"), 0)).toBe("178");
  });

  it("keeps the sign on a negative", () => {
    expect(formatUsd(-parseUsd("12.34"))).toBe("-12.34");
    expect(formatUsd(-parseUsd("12.34"), 0)).toBe("-12");
  });

  it("tolerates thousands separators", () => {
    expect(parseUsd("1,234.56")).toBe(123456000000n);
  });
});

describe("dated series", () => {
  it("matures 22 hours after the trading day starts", () => {
    const day = tradingDayFor(new Date("2026-09-11T00:00:00Z"));
    expect(maturityFor(day)).toBe(day * 86_400n + 22n * 3600n);
    expect(new Date(Number(maturityFor(day)) * 1000).toISOString()).toBe("2026-09-11T22:00:00.000Z");
  });
});
